# Generated by Django 4.2.4 on 2023-10-30 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typequiz',
            name='quiz_id',
            field=models.UUIDField(default=uuid.UUID('6925f957-b795-439d-b591-3992b29b2dbc')),
        ),
    ]
